version: '3'

networks:
  gb-yii:
    driver: bridge

services:
  app:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    ports:
      - "80:80"
    networks:
      - gb-yii
    depends_on:
      - db
    volumes:
      - "./:/var/www/app"
      - "./docker/conf/nginx:/etc/nginx/sites-available"

  db:
    container_name: mysql_gb_yii2
    image: 'mysql:latest'
    networks:
      - gb-yii
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: yii2basic
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: mysqluser
    volumes:
      - ./docker/database:/var/lib/mysql